[workspace]
authors = ["notPlancha <andre.plancha@hotmail.com>"]
channels = ["conda-forge"]
name = "eda-exam"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
jupyter = ">=1.1.1,<2"
numpy = ">=2.2.4,<3"
pandas = ">=2.2.3,<3"
scikit-learn = ">=1.6.1,<2"
scipy = ">=1.15.2,<2"
plotnine = ">=0.14.5,<0.15"
pyprojroot = ">=0.3.0,<0.4"
tqdm = ">=4.67.1,<5"
sympy = ">=1.13.3,<2"
plotly = ">=6.0.1,<7"
joblib = ">=1.4.2,<2"

[pypi-dependencies]
pyedakit = ">=0.1.4, <0.2"
